/* Help page copy in the app's language order. Display text only. */
(function(){'use strict';
 const rows = [
  ["帮助","Help","Aide","Справка","Ayuda","ヘルプ","Ajuda","Hilfe","Помоћ","도움말"],
  ["服务器协作与离线合并","Server collaboration and offline merging","Collaboration via serveur et fusion hors ligne","Совместная работа на сервере и автономное объединение","Colaboración en servidor y combinación sin conexión","サーバー共同作業とオフライン統合","Colaboração no servidor e consolidação offline","Serverzusammenarbeit und Offline-Zusammenführung","Сарадња преко сервера и спајање ван мреже","서버 협업 및 오프라인 병합"],
  ["选择使用方式","Choose how to work","Choisir un mode d’utilisation","Выберите режим работы","Elija cómo trabajar","利用方法を選択","Escolha como trabalhar","Nutzungsart wählen","Изаберите начин рада","사용 방식 선택"],
  ["个人离线使用","Personal offline use","Utilisation personnelle hors ligne","Личное использование без сети","Uso personal sin conexión","個人でオフライン利用","Uso pessoal offline","Persönliche Offline-Nutzung","Лична употреба ван мреже","개인 오프라인 사용"],
  ["数据保存在本机","Data stays on this device","Les données restent sur cet appareil","Данные хранятся на этом устройстве","Los datos se guardan en este dispositivo","データはこの端末に保存されます","Os dados ficam neste dispositivo","Daten bleiben auf diesem Gerät","Подаци се чувају на овом уређају","데이터는 이 기기에 저장됩니다"],
  ["服务器协作","Server collaboration","Collaboration via serveur","Совместная работа на сервере","Colaboración en servidor","サーバー共同作業","Colaboração no servidor","Serverzusammenarbeit","Сарадња преко сервера","서버 협업"],
  ["数据保存在此服务器","Data is stored on this server","Les données sont stockées sur ce serveur","Данные хранятся на этом сервере","Los datos se guardan en este servidor","データはこのサーバーに保存されます","Os dados são armazenados neste servidor","Daten werden auf diesem Server gespeichert","Подаци се чувају на овом серверу","데이터는 이 서버에 저장됩니다"],
  ["每位成员先在同一服务器注册账号。","Each member must first register an account on the same server.","Chaque membre doit d’abord créer un compte sur le même serveur.","Каждому участнику сначала нужно зарегистрировать аккаунт на одном сервере.","Cada miembro debe registrarse primero en el mismo servidor.","各メンバーは、まず同じサーバーにアカウントを登録します。","Cada membro deve primeiro criar uma conta no mesmo servidor.","Jedes Mitglied muss zuerst ein Konto auf demselben Server registrieren.","Сваки члан прво треба да региструје налог на истом серверу.","각 구성원은 먼저 같은 서버에 계정을 등록해야 합니다."],
  ["任务属主按用户名添加成员，授予筛选与编码或仲裁权限。","The task owner adds members by username and grants screening and coding or adjudication permissions.","Le propriétaire de la tâche ajoute les membres par nom d’utilisateur et leur attribue les droits de sélection et de codage ou d’arbitrage.","Владелец задачи добавляет участников по имени пользователя и назначает им права на отбор и кодирование или разрешение разногласий.","El propietario de la tarea añade miembros por nombre de usuario y les concede permisos de selección y codificación o arbitraje.","タスク所有者はユーザー名でメンバーを追加し、スクリーニングとコーディングまたは判定の権限を付与します。","O proprietário da tarefa adiciona membros pelo nome de usuário e concede permissões de triagem e codificação ou arbitragem.","Der Aufgabeninhaber fügt Mitglieder über ihren Benutzernamen hinzu und erteilt Rechte für Screening und Codierung oder Klärung von Konflikten.","Власник задатка додаје чланове према корисничком имену и додељује им права за селекцију и кодирање или решавање несугласица.","작업 소유자는 사용자 이름으로 구성원을 추가하고 선별 및 코딩 또는 판정 권한을 부여합니다."],
  ["属主导入文献，成员打开文献列表时会取得同一文献目录。","The owner imports references. When members open the reference list, they get the same list.","Le propriétaire importe les références. Lorsque les membres ouvrent la liste des références, ils obtiennent la même liste.","Владелец импортирует публикации. Когда участники открывают список публикаций, они получают тот же список.","El propietario importa las referencias. Al abrir la lista de referencias, los miembros reciben la misma lista.","所有者が文献をインポートすると、メンバーは文献一覧を開いたときに同じ一覧を取得します。","O proprietário importa as referências. Ao abrir a lista de referências, os membros recebem a mesma lista.","Der Inhaber importiert die Referenzen. Beim Öffnen der Referenzliste erhalten Mitglieder dieselbe Liste.","Власник увози референце. Када чланови отворе листу референци, добијају исту листу.","소유자가 문헌을 가져오면 구성원은 문헌 목록을 열 때 같은 목록을 받습니다."],
  ["团队进度只显示完成数量，个人决策由本人账号保存。","Team progress shows only completion counts; each person’s decisions are saved to their own account.","Le progrès de l’équipe n’affiche que le nombre de tâches terminées ; les décisions de chacun sont enregistrées dans son compte.","В командном прогрессе отображается только число завершённых работ; решения каждого участника сохраняются в его аккаунте.","El progreso del equipo solo muestra el número de tareas completadas; las decisiones se guardan en la cuenta de cada persona.","チームの進捗には完了数のみが表示され、個人の判定は各自のアカウントに保存されます。","O progresso da equipe mostra apenas o número de tarefas concluídas; as decisões de cada pessoa são salvas na própria conta.","Der Teamfortschritt zeigt nur die Anzahl abgeschlossener Aufgaben. Entscheidungen werden im jeweiligen Konto gespeichert.","Напредак тима приказује само број завршених ставки; одлуке сваког члана чувају се на његовом налогу.","팀 진행 상황에는 완료 수만 표시되며 개인 결정은 각자의 계정에 저장됩니다."],
  ["导出每位筛选员的初筛或复筛 CSV。","Export a CSV of each screener’s first- or second-round screening.","Exporter en CSV le premier ou le second tri de chaque évaluateur.","Экспортируйте CSV первичного или повторного отбора каждого участника.","Exporte en CSV la primera o segunda ronda de selección de cada revisor.","各スクリーナーの一次または二次スクリーニングを CSV でエクスポートします。","Exporte em CSV a primeira ou segunda etapa de triagem de cada revisor.","Exportieren Sie das Erst- oder Zweitscreening jeder prüfenden Person als CSV.","Извезите CSV примарне или поновљене селекције за сваког оцењивача.","각 선별 담당자의 1차 또는 2차 선별 결과를 CSV로 내보냅니다."],
  ["在合并仲裁页上传 2–9 份同阶段文件。","On the merge and adjudication page, upload 2–9 files from the same stage.","Dans la page Fusion et arbitrage, importer 2 à 9 fichiers de la même étape.","На странице объединения и разрешения разногласий загрузите 2–9 файлов одного этапа.","En la página de combinación y arbitraje, suba de 2 a 9 archivos de la misma fase.","統合・判定ページで、同じ段階のファイルを 2～9 件アップロードします。","Na página de consolidação e arbitragem, envie de 2 a 9 arquivos da mesma etapa.","Laden Sie auf der Seite für Zusammenführung und Konfliktklärung 2–9 Dateien derselben Phase hoch.","На страници за спајање и решавање несугласица отпремите 2–9 датотека из исте фазе.","병합 및 판정 페이지에서 같은 단계의 파일을 2~9개 업로드합니다."],
  ["逐条选择仲裁结论并保存","Choose and save an adjudication result for each item","Choisissez et enregistrez une conclusion d’arbitrage pour chaque élément","Выберите и сохраните итоговое решение по каждому пункту","Elija y guarde una decisión de arbitraje para cada elemento","各項目の判定結果を選択して保存します","Escolha e salve uma decisão de arbitragem para cada item","Wählen Sie für jeden Eintrag die abschließende Klärungsentscheidung und speichern Sie sie","Изаберите и сачувајте коначну одлуку за сваку ставку","항목별 판정 결과를 선택하고 저장합니다"],
  ["原始个人决策不会改变。","Original individual decisions remain unchanged.","Les décisions individuelles d’origine restent inchangées.","Исходные индивидуальные решения не изменяются.","Las decisiones individuales originales no cambian.","元の個人判定は変更されません。","As decisões individuais originais permanecem inalteradas.","Die ursprünglichen Einzelentscheidungen bleiben unverändert.","Првобитне појединачне одлуке остају непромењене.","원래의 개인 결정은 변경되지 않습니다."],
  ["可从最近的仲裁记录导出 JSON。","Export JSON from recent adjudication records.","Exporter le JSON depuis les derniers arbitrages.","Экспортируйте JSON из последних записей о разрешении разногласий.","Exporte JSON desde los registros recientes de arbitraje.","最近の判定記録から JSON をエクスポートできます。","Exporte JSON dos registros recentes de arbitragem.","JSON aus den letzten Entscheidungsprotokollen exportieren.","Извезите JSON из недавних записа о решавању несугласица.","최근 판정 기록에서 JSON을 내보낼 수 있습니다."],
  ["所有人应从同一份文献目录开始，以便文献键一致。","Everyone should start with the same reference list so reference keys match.","Tout le monde doit partir du même catalogue de références pour conserver les mêmes clés.","Всем следует начать с одного списка публикаций, чтобы ключи публикаций совпадали.","Todos deben partir de la misma lista de referencias para que coincidan las claves.","文献キーを一致させるため、全員が同じ文献一覧から作業を始めてください。","Todos devem começar com a mesma lista de referências para manter as mesmas chaves.","Alle sollten mit derselben Referenzliste beginnen, damit die Referenzschlüssel übereinstimmen.","Сви треба да почну са исте листе референци како би кључеви били усклађени.","문헌 키를 일치시키려면 모두 같은 문헌 목록에서 시작해야 합니다."],
  ["离线用户各自保管和备份自己的数据。","Offline users are responsible for keeping and backing up their own data.","En mode hors ligne, chacun conserve et sauvegarde ses propres données.","При работе без сети каждый пользователь сам хранит и резервирует свои данные.","Quienes trabajan sin conexión deben conservar y respaldar sus propios datos.","オフライン利用者は各自でデータを保管し、バックアップしてください。","Quem trabalha offline deve guardar e fazer backup dos próprios dados.","Offline-Nutzer bewahren ihre Daten selbst auf und sichern sie selbst.","Корисници ван мреже сами чувају и праве резервне копије својих података.","오프라인 사용자는 각자 데이터를 보관하고 백업해야 합니다."],
  ["服务器部署示例","Server deployment example","Exemple de déploiement sur serveur","Пример развёртывания на сервере","Ejemplo de implementación en servidor","サーバーへの導入例","Exemplo de implantação no servidor","Beispiel für die Serverbereitstellung","Пример постављања на сервер","서버 배포 예시"],
  ["将数据目录改为服务器上可持久保存的位置。","Set the data directory to a persistent location on the server.","Définissez le dossier de données sur un emplacement persistant du serveur.","Укажите для каталога данных постоянное место на сервере.","Configure el directorio de datos en una ubicación persistente del servidor.","データディレクトリをサーバー上の永続保存先に設定します。","Defina o diretório de dados em um local persistente no servidor.","Legen Sie das Datenverzeichnis an einem dauerhaften Speicherort auf dem Server ab.","Подесите директоријум података на трајну локацију на серверу.","데이터 디렉터리를 서버의 영구 저장 위치로 설정하세요."],
  ["服务器管理员应备份服务器数据目录并通过 HTTPS 提供访问。","Server administrators should back up the server data directory and provide access over HTTPS.","Les administrateurs doivent sauvegarder le dossier de données du serveur et fournir l’accès via HTTPS.","Администраторы сервера должны резервировать каталог данных и предоставлять доступ по HTTPS.","Los administradores deben respaldar el directorio de datos del servidor y ofrecer acceso mediante HTTPS.","サーバー管理者はサーバーのデータディレクトリをバックアップし、HTTPS 経由でアクセスを提供してください。","Os administradores devem fazer backup do diretório de dados do servidor e oferecer acesso por HTTPS.","Serveradministratoren sollten das Serverdatenverzeichnis sichern und den Zugriff über HTTPS bereitstellen.","Администратори сервера треба да праве резервне копије директоријума са подацима и омогуће приступ преко HTTPS-а.","서버 관리자는 서버 데이터 디렉터리를 백업하고 HTTPS로 접속을 제공해야 합니다."],
  ["更多使用说明。","More usage instructions.","Plus d’instructions d’utilisation.","Дополнительные инструкции.","Más instrucciones de uso.","詳しい使い方。","Mais instruções de uso.","Weitere Nutzungshinweise.","Још упутстава за употребу.","자세한 사용 안내."],
  ["打开合并仲裁","Open merge and adjudication","Accéder à la fusion et à l’arbitrage","Открыть объединение и разрешение разногласий","Abrir combinación y arbitraje","統合・判定を開く","Abrir consolidação e arbitragem","Zusammenführung und Konfliktklärung öffnen","Отворите спајање и решавање несугласица","병합 및 판정 열기"],
  ["打开导出决策","Open decision export","Ouvrir l’export des décisions","Открыть экспорт решений","Abrir exportación de decisiones","判定のエクスポートを開く","Abrir exportação de decisões","Entscheidungsexport öffnen","Отвори извоз одлука","결정 내보내기 열기"],
  ["打开任务首页","Open task home","Ouvrir l’accueil de la tâche","Открыть главную страницу задачи","Abrir inicio de la tarea","タスクのホームを開く","Abrir página inicial da tarefa","Aufgabenstartseite öffnen","Отвори почетну страницу задатка","작업 홈 열기"],
  ["团队进度","Team progress","Progression de l’équipe","Командный прогресс","Progreso del equipo","チーム進捗","Progresso da equipe","Teamfortschritt","Напредак тима","팀 진행 상황"],
  ["此服务器保存任务数据","Task data is stored on this server","Les données des tâches sont stockées sur ce serveur","Данные задач хранятся на этом сервере","Los datos de las tareas se guardan en este servidor","タスクデータはこのサーバーに保存されます","Os dados das tarefas são armazenados neste servidor","Aufgabendaten werden auf diesem Server gespeichert","Подаци задатака се чувају на овом серверу","작업 데이터는 이 서버에 저장됩니다"],
  ["这里只显示完成数量。每个人的筛选决定仍由本人保存；仲裁结果单独记录。","Only completion counts appear here. Each person’s screening decisions remain in their own account; adjudication results are recorded separately.","Seul le nombre de tâches terminées s’affiche ici. Les décisions de sélection restent dans le compte de chacun ; les résultats d’arbitrage sont consignés séparément.","Здесь отображается только число завершённых пунктов. Решения каждого участника по отбору остаются в его аккаунте; результаты разрешения разногласий записываются отдельно.","Aquí solo se muestra el número de elementos completados. Las decisiones de selección de cada persona se guardan en su cuenta; los resultados del arbitraje se registran por separado.","ここには完了数のみ表示されます。各自のスクリーニング判定は本人のアカウントに保存され、仲裁結果は別に記録されます。","Aqui só aparece o número de itens concluídos. As decisões de triagem de cada pessoa permanecem na própria conta; os resultados da arbitragem são registrados à parte.","Hier wird nur die Anzahl abgeschlossener Einträge angezeigt. Screening-Entscheidungen bleiben im jeweiligen Konto; Ergebnisse der Konfliktklärung werden separat erfasst.","Овде се приказује само број завршених ставки. Одлуке сваког члана о селекцији остају на његовом налогу; исходи решавања несугласица бележе се засебно.","여기에는 완료 수만 표시됩니다. 각자의 선별 결정은 본인 계정에 저장되고 판정 결과는 별도로 기록됩니다."],
  ["已注册用户的用户名","Registered username","Nom d’utilisateur enregistré","Имя зарегистрированного пользователя","Nombre de usuario registrado","登録済みユーザー名","Nome de usuário cadastrado","Benutzername eines registrierten Kontos","Корисничко име регистрованог корисника","등록된 사용자 이름"],
  ["协作权限","Collaboration permissions","Droits de collaboration","Права совместной работы","Permisos de colaboración","共同作業の権限","Permissões de colaboração","Zusammenarbeitsrechte","Права за сарадњу","협업 권한"],
  ["筛选与编码","Screening and coding","Sélection et codage","Отбор и кодирование","Selección y codificación","スクリーニングとコーディング","Triagem e codificação","Screening und Codierung","Селекција и кодирање","선별 및 코딩"],
  ["仲裁员","Adjudicator","Arbitre","Разрешение разногласий","Árbitro","判定者","Árbitro","Konfliktklärung","Решавање несугласица","판정자"],
  ["添加成员","Add member","Ajouter un membre","Добавить участника","Añadir miembro","メンバーを追加","Adicionar membro","Mitglied hinzufügen","Додај члана","구성원 추가"],
  ["暂无成员进度。","No member progress yet.","Aucune progression des membres pour le moment.","Пока нет данных о прогрессе участников.","Aún no hay datos de progreso de los miembros.","メンバーの進捗はまだありません。","Ainda não há progresso dos membros.","Noch kein Mitgliederfortschritt.","Још нема података о напретку чланова.","아직 구성원 진행 상황이 없습니다."],
  ["请输入用户名。","Enter a username.","Saisissez un nom d’utilisateur.","Введите имя пользователя.","Introduzca un nombre de usuario.","ユーザー名を入力してください。","Digite um nome de usuário.","Benutzernamen eingeben.","Унесите корисничко име.","사용자 이름을 입력하세요."],
  ["该账号不存在。请对方先在此服务器注册。","Account not found. Ask them to register on this server first.","Compte introuvable. Demandez à cette personne de s’inscrire d’abord sur ce serveur.","Аккаунт не найден. Попросите пользователя сначала зарегистрироваться на этом сервере.","No se encontró la cuenta. Pídale que se registre primero en este servidor.","アカウントが見つかりません。このサーバーに先に登録するよう伝えてください。","Conta não encontrada. Peça à pessoa que se cadastre primeiro neste servidor.","Konto nicht gefunden. Die Person muss sich zuerst auf diesem Server registrieren.","Налог није пронађен. Замолите ту особу да се прво региструје на овом серверу.","계정을 찾을 수 없습니다. 먼저 이 서버에 가입하도록 안내하세요."],
  ["筛选阶段","Screening stage","Étape de sélection","Этап отбора","Fase de selección","スクリーニング段階","Etapa de triagem","Screening-Phase","Фаза селекције","선별 단계"],
  ["最近的仲裁记录","Recent adjudication records","Arbitrages récents","Последние записи о разрешении разногласий","Registros recientes de arbitraje","最近の判定記録","Registros recentes de arbitragem","Letzte Entscheidungsprotokolle","Недавни записи о решавању несугласица","최근 판정 기록"],
  ["导出仲裁记录","Export adjudication records","Exporter les arbitrages","Экспорт записей о разрешении разногласий","Exportar registros de arbitraje","判定記録をエクスポート","Exportar registros de arbitragem","Entscheidungsprotokolle exportieren","Извезите записе о решавању несугласица","판정 기록 내보내기"],
  ["保存仲裁记录","Save adjudication record","Enregistrer l’arbitrage","Сохранить запись о разрешении разногласий","Guardar registro de arbitraje","判定記録を保存","Salvar registro de arbitragem","Entscheidungsprotokoll speichern","Сачувајте запис о решавању несугласица","판정 기록 저장"],
  ["待仲裁","Pending adjudication","En attente d’arbitrage","Ожидает итогового решения","Pendiente de arbitraje","判定待ち","Pendente de arbitragem","Entscheidung ausstehend","Чека коначну одлуку","판정 대기"],
  ["仲裁说明（可选）","Adjudication notes (optional)","Notes d’arbitrage (facultatif)","Примечание к разрешению разногласий (необязательно)","Notas de arbitraje (opcional)","判定メモ（任意）","Observações da arbitragem (opcional)","Hinweis zur Konfliktklärung (optional)","Напомена о решавању несугласица (опционо)","판정 메모(선택 사항)"],
  ["请重新选择这一阶段的决策 CSV","Please reselect the decision CSV for this stage","Veuillez sélectionner à nouveau le CSV de décisions de cette étape","Повторно выберите CSV решений для этого этапа","Vuelva a seleccionar el CSV de decisiones de esta fase","この段階の判定 CSV を選び直してください","Selecione novamente o CSV de decisões desta etapa","Wählen Sie die Entscheidungs-CSV für diese Phase erneut aus","Поново изаберите CSV одлука за ову фазу","이 단계의 결정 CSV를 다시 선택하세요"],
  ["请先选择任务，并重新上传该任务的决策 CSV。","Select a task first, then reupload its decision CSV.","Sélectionnez d’abord une tâche, puis importez à nouveau son CSV de décisions.","Сначала выберите задачу, затем повторно загрузите CSV её решений.","Seleccione primero una tarea y vuelva a subir su CSV de decisiones.","先にタスクを選択し、そのタスクの判定 CSV を再アップロードしてください。","Selecione uma tarefa primeiro e envie novamente o CSV de decisões dela.","Wählen Sie zuerst eine Aufgabe aus und laden Sie deren Entscheidungs-CSV erneut hoch.","Прво изаберите задатак, а затим поново отпремите његов CSV одлука.","먼저 작업을 선택한 다음 해당 작업의 결정 CSV를 다시 업로드하세요."],
  ["仲裁记录 #{0} 已保存；{1} 条仍待仲裁。个人原始决策未改动。","Adjudication record #{0} saved; {1} items still pending. Original individual decisions are unchanged.","Arbitrage #{0} enregistré ; {1} éléments restent à traiter. Les décisions individuelles d’origine sont inchangées.","Запись об итоговом решении #{0} сохранена; ожидают решения: {1}. Исходные индивидуальные решения не изменены.","Registro de arbitraje #{0} guardado; quedan {1} elementos pendientes. Las decisiones individuales originales no se modificaron.","判定記録 #{0} を保存しました。{1} 件が判定待ちです。個人の元の判定は変更されていません。","Registro de arbitragem #{0} salvo; {1} itens ainda aguardam decisão. As decisões individuais originais não foram alteradas.","Entscheidungsprotokoll #{0} gespeichert; offene Einträge: {1}. Die ursprünglichen Einzelentscheidungen bleiben unverändert.","Запис о решавању несугласица #{0} је сачуван; број ставки на чекању: {1}. Појединачне одлуке нису промењене.","판정 기록 #{0}을 저장했습니다. {1}개 항목이 아직 대기 중입니다. 개인의 원래 결정은 변경되지 않았습니다."],
  ["最近记录 #{0}：{1} 条，{2} 条待仲裁。","Latest record #{0}: {1} items, {2} pending.","Dernier enregistrement #{0} : {1} éléments, dont {2} en attente.","Последняя запись #{0}: всего пунктов — {1}; ожидают решения — {2}.","Registro más reciente #{0}: {1} elementos, {2} pendientes.","最新記録 #{0}：{1} 件、うち {2} 件が判定待ちです。","Registro mais recente #{0}: {1} itens, {2} pendentes.","Letztes Protokoll #{0}: {1} Einträge, davon {2} offen.","Најновији запис #{0}: укупан број ставки — {1}; на чекању — {2}.","최근 기록 #{0}: {1}개 항목, {2}개 대기 중."],
  ["{0} / {1} · {2} 条","{0} / {1} · {2} items","{0} / {1} · {2} éléments","{0} / {1} · пунктов: {2}","{0} / {1} · {2} elementos","{0} / {1} · {2} 件","{0} / {1} · {2} itens","{0} / {1} · {2} Einträge","{0} / {1} · број ставки: {2}","{0} / {1} · {2}개 항목"]
 ];
 RFLang.register(rows);
})();

// Keep in-page help navigation separate from the application's route hash.
document.addEventListener('click',function(event){
 const link=event.target.closest('.help-contents a');
 if(!link)return;
 const target=document.getElementById(link.getAttribute('href').slice(1));
 if(!target)return;
 event.preventDefault();
 const heading=target.querySelector('h3');
 if(heading){heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true});}
 target.scrollIntoView({block:'start'});
});
