/* Stable schema keys stay untranslated; only product labels are localized. */
(function(){'use strict';RFLang.register([
['导入历史','Import history','Historique des importations','История импорта','Historial de importaciones','インポート履歴','Histórico de importações','Importverlauf',"Историја увоза",'가져오기 기록'],
['查看每次上传的原文件与导入结果。','View the original file and import result for each upload.','Consultez le fichier d’origine et le résultat de chaque importation.','Просмотр исходного файла и результата каждого импорта.','Consulta el archivo original y el resultado de cada importación.','アップロードごとの元ファイルとインポート結果を確認できます。','Consulte o arquivo original e o resultado de cada importação.','Originaldatei und Importergebnis jedes Uploads ansehen.',"Погледајте оригиналну датотеку и резултат сваког увоза.",'업로드별 원본 파일과 가져오기 결과를 확인합니다.'],
['尚无导入历史','No import history yet','Aucun historique d’importation pour le moment','Истории импорта пока нет','Aún no hay historial de importaciones','インポート履歴はまだありません','Ainda não há histórico de importações','Noch kein Importverlauf vorhanden',"Још нема историје увоза",'아직 가져오기 기록이 없습니다'],
['原文件','Original file','Fichier d’origine','Исходный файл','Archivo original','元ファイル','Arquivo original','Originaldatei',"Оригинална датотека",'원본 파일'],
['下载原文件','Download original file','Télécharger le fichier d’origine','Скачать исходный файл','Descargar archivo original','元ファイルをダウンロード','Baixar arquivo original','Originaldatei herunterladen',"Преузми оригиналну датотеку",'원본 파일 다운로드'],
['导入时间','Import time','Date d’importation','Время импорта','Fecha de importación','インポート日時','Data da importação','Importzeit',"Време увоза",'가져온 시간'],
['文件名','File name','Nom du fichier','Имя файла','Nombre del archivo','ファイル名','Nome do arquivo','Dateiname',"Назив датотеке",'파일 이름'],
['文件大小','File size','Taille du fichier','Размер файла','Tamaño del archivo','ファイルサイズ','Tamanho do arquivo','Dateigröße',"Величина датотеке",'파일 크기'],
['导入结果','Import result','Résultat de l’importation','Результат импорта','Resultado de la importación','インポート結果','Resultado da importação','Importergebnis',"Резултат увоза",'가져오기 결과'],
['解析','Parsed','Analysées','Обработано','Analizados','解析','Analisados','Geparst',"Обрађено",'분석'],
['导入','Imported','Importées','Импортировано','Importados','インポート済み','Importados','Importiert',"Увезено",'가져옴'],
['重复','Duplicates','Doublons','Дубликаты','Duplicados','重複','Duplicados','Duplikate',"Дупликати",'중복'],
['原文件已保存，可下载核对；仅包含启用此功能后的导入。','Original files are saved and available to download for checking; only imports made after this feature was enabled are included.','Les fichiers d’origine sont enregistrés et peuvent être téléchargés pour vérification ; seuls les imports effectués après l’activation de cette fonction sont inclus.','Исходные файлы сохранены и доступны для скачивания и проверки; включены только импорты, выполненные после включения этой функции.','Los archivos originales se guardan y se pueden descargar para revisarlos; solo se incluyen las importaciones realizadas después de activar esta función.','元ファイルは保存され、ダウンロードして確認できます。この機能を有効にした後のインポートのみが対象です。','Os arquivos originais são salvos e podem ser baixados para conferência; somente importações feitas após a ativação deste recurso são incluídas.','Originaldateien werden gespeichert und können zur Prüfung heruntergeladen werden. Enthalten sind nur Importe nach Aktivierung dieser Funktion.',"Оригиналне датотеке су сачуване и могу се преузети ради провере; обухваћени су само увози након што је ова функција омогућена.",'원본 파일이 저장되어 다운로드해 확인할 수 있습니다. 이 기능을 사용 설정한 후 가져온 항목만 포함됩니다.'],
['文件校验值','File checksum','Somme de contrôle du fichier','Контрольная сумма файла','Suma de verificación del archivo','ファイルチェックサム','Soma de verificação do arquivo','Datei-Prüfsumme',"Контролна сума датотеке",'파일 체크섬'],
['历史加载失败，请重试。','Could not load import history. Please try again.','Impossible de charger l’historique. Veuillez réessayer.','Не удалось загрузить историю. Повторите попытку.','No se pudo cargar el historial. Inténtalo de nuevo.','履歴を読み込めませんでした。もう一度お試しください。','Não foi possível carregar o histórico. Tente novamente.','Der Verlauf konnte nicht geladen werden. Bitte versuchen Sie es erneut.',"Учитавање историје није успело. Покушајте поново.",'기록을 불러오지 못했습니다. 다시 시도하세요.'],
['刷新历史','Refresh history','Actualiser l’historique','Обновить историю','Actualizar historial','履歴を更新','Atualizar histórico','Verlauf aktualisieren',"Освежи историју",'기록 새로고침']
]);})();
