(function () {
  'use strict';
  RFLang.register([
    ['正在导入文献', 'Importing references', 'Importation des références', 'Импорт публикаций', 'Importando referencias', '文献をインポート中', 'Importando referências', 'Referenzen werden importiert', 'Увоз публикација', '문헌 가져오는 중'],
    ['导入与去重进度', 'Import and deduplication progress', 'Progression de l’importation et du dédoublonnage', 'Ход импорта и дедупликации', 'Progreso de importación y deduplicación', 'インポートと重複除去の進捗', 'Progresso da importação e deduplicação', 'Fortschritt beim Import und Deduplizieren', 'Напредак увоза и дедупликације', '가져오기 및 중복 제거 진행률'],
    ['正在解析文件并准备去重…', 'Parsing files and preparing deduplication…', 'Analyse des fichiers et préparation du dédoublonnage…', 'Анализ файлов и подготовка к дедупликации…', 'Analizando archivos y preparando la deduplicación…', 'ファイルを解析して重複除去を準備中…', 'Analisando arquivos e preparando a deduplicação…', 'Dateien werden analysiert und die Deduplizierung vorbereitet…', 'Анализа датотека и припрема дедупликације…', '파일을 분석하고 중복 제거를 준비하는 중…'],
    ['正在进行精确去重…', 'Running exact deduplication…', 'Dédoublonnage exact en cours…', 'Выполняется точная дедупликация…', 'Realizando la deduplicación exacta…', '完全一致の重複を除去中…', 'Executando deduplicação exata…', 'Exakte Deduplizierung läuft…', 'Тачна дедупликација је у току…', '정확 중복 제거 중…'],
    ['精确匹配已完成，正在分段查找标题和作者相似候选…', 'Exact matching is complete; finding similar-title-and-author candidates in chunks…', 'Les correspondances exactes sont terminées ; recherche par blocs de titres et auteurs similaires…', 'Точные совпадения обработаны; поиск похожих заголовков и авторов по частям…', 'Coincidencias exactas completas; buscando títulos y autores similares por bloques…', '完全一致の照合が完了しました。タイトルと著者が似た候補を分割して検索中…', 'Correspondências exatas concluídas; procurando títulos e autores semelhantes em blocos…', 'Exakte Treffer sind abgeschlossen; ähnliche Titel und Autoren werden blockweise gesucht…', 'Тачна поклапања су завршена; претрага сличних наслова и аутора по блоковима…', '정확 일치 검사가 끝났습니다. 제목과 저자가 비슷한 후보를 묶음 단위로 찾는 중…'],
    ['匹配已完成，正在保存导入结果…', 'Matching is complete; saving imported records…', 'Comparaison terminée ; enregistrement des références importées…', 'Сопоставление завершено; сохранение импортированных записей…', 'Comparación completa; guardando los registros importados…', '照合が完了しました。インポート結果を保存中…', 'Correspondência concluída; salvando os registros importados…', 'Abgleich abgeschlossen; importierte Einträge werden gespeichert…', 'Поређење је завршено; чување увезених записа…', '일치 확인이 끝났습니다. 가져온 문헌을 저장하는 중…'],
    ['模糊匹配候选记录数（待人工核验）', 'Fuzzy-match candidate records (awaiting review)', 'Entrées candidates au rapprochement flou (à vérifier)', 'Кандидаты нечеткого совпадения (ожидают проверки)', 'Registros candidatos por coincidencia difusa (pendientes de revisión)', '類似一致の候補レコード（人手確認待ち）', 'Registos candidatos a correspondência aproximada (aguardam revisão)', 'Kandidaten für unscharfe Treffer (manuelle Prüfung ausstehend)', 'Кандидати нејасног поклапања (чекају проверу)', '유사도 일치 후보 문헌 (검토 대기)'],
    ['精确去重后记录数（含待核验候选）', 'Records after exact deduplication (including candidates awaiting review)', 'Entrées après dédoublonnage exact (y compris les candidates à vérifier)', 'Записи после точной дедупликации (включая кандидатов на проверке)', 'Registros tras deduplicación exacta (incluye candidatos pendientes de revisión)', '完全一致の重複除去後の件数（確認待ち候補を含む）', 'Registos após deduplicação exata (inclui candidatos aguardando revisão)', 'Einträge nach exakter Deduplizierung (einschließlich Kandidaten in Prüfung)', 'Записи након тачне дедупликације (укључујући кандидате на провери)', '정확 중복 제거 후 문헌 수 (검토 대기 후보 포함)'],
  ]);
})();
