(function(){'use strict';RFLang.register([
['重启软件','Restart app','Redémarrer l’application','Перезапустить приложение','Reiniciar la aplicación','アプリを再起動','Reiniciar o aplicativo','App neu starten','Поново покрени апликацију','앱 다시 시작'],
['将等待当前保存完成，然后重启 ReviewFlow。未提交的表单内容请先保存。现在重启吗？','ReviewFlow will wait for current saves, then restart. Save any form changes you have not submitted. Restart now?','ReviewFlow attendra la fin des enregistrements en cours, puis redémarrera. Enregistrez les formulaires non envoyés. Redémarrer maintenant ?','ReviewFlow дождётся завершения сохранения и перезапустится. Сохраните несохранённые изменения в формах. Перезапустить сейчас?','ReviewFlow esperará a que terminen los guardados y se reiniciará. Guarda los cambios de formularios que no hayas enviado. ¿Reiniciar ahora?','現在の保存が完了してからReviewFlowを再起動します。未送信のフォーム内容を保存してください。今すぐ再起動しますか？','O ReviewFlow aguardará os salvamentos atuais e será reiniciado. Salve as alterações de formulários ainda não enviadas. Reiniciar agora?','ReviewFlow wartet aktuelle Speichervorgänge ab und startet dann neu. Speichern Sie nicht übermittelte Formulare. Jetzt neu starten?','ReviewFlow ће сачекати завршетак чувања, па се поново покренути. Сачувајте непослате измене у обрасцима. Покренути сада?','현재 저장이 끝나면 ReviewFlow가 다시 시작됩니다. 제출하지 않은 양식 내용을 저장하세요. 지금 다시 시작할까요?'],
['正在保存并重启…','Saving and restarting…','Enregistrement et redémarrage…','Сохранение и перезапуск…','Guardando y reiniciando…','保存して再起動中…','Salvando e reiniciando…','Speichern und Neustarten…','Чување и поновно покретање…','저장 및 다시 시작 중…'],
['请稍候，当前保存操作完成后会自动重新打开页面。','Please wait. The page will reopen when current saves are complete.','Veuillez patienter. La page se rouvrira une fois les enregistrements terminés.','Подождите. Страница откроется снова после завершения сохранения.','Espera. La página se volverá a abrir cuando terminen los guardados.','お待ちください。保存が完了するとページが自動で再表示されます。','Aguarde. A página será reaberta quando os salvamentos terminarem.','Bitte warten. Die Seite wird nach Abschluss der Speichervorgänge erneut geöffnet.','Сачекајте. Страница ће се поново отворити када се чување заврши.','잠시 기다려 주세요. 저장이 끝나면 페이지가 자동으로 다시 열립니다.'],
['保存仍在进行，暂时无法重启。请稍后再试。','A save is still in progress, so the app cannot restart yet. Please try again shortly.','Un enregistrement est toujours en cours. Impossible de redémarrer pour le moment. Réessayez bientôt.','Сохранение ещё выполняется, поэтому перезапуск пока невозможен. Повторите попытку позже.','Aún hay un guardado en curso, así que no se puede reiniciar todavía. Inténtalo de nuevo pronto.','保存処理中のため、まだ再起動できません。しばらくしてから再試行してください。','Ainda há um salvamento em andamento, então não é possível reiniciar agora. Tente novamente em instantes.','Ein Speichervorgang läuft noch. Die App kann derzeit nicht neu starten. Bitte versuchen Sie es gleich erneut.','Чување је још у току, па апликација још не може да се поново покрене. Покушајте ускоро поново.','저장 작업이 진행 중이라 아직 다시 시작할 수 없습니다. 잠시 후 다시 시도하세요.'],
['正在重启软件…','Restarting app…','Redémarrage de l’application…','Перезапуск приложения…','Reiniciando la aplicación…','アプリを再起動中…','Reiniciando o aplicativo…','App wird neu gestartet…','Апликација се поново покреће…','앱 다시 시작 중…'],
['服务尚未恢复。请稍后手动刷新页面。','The service has not returned yet. Please refresh the page manually later.','Le service n’est pas encore rétabli. Actualisez la page manuellement plus tard.','Сервис ещё не восстановился. Позже обновите страницу вручную.','El servicio aún no está disponible. Actualiza la página manualmente más tarde.','サービスはまだ復旧していません。後で手動でページを更新してください。','O serviço ainda não voltou. Atualize a página manualmente mais tarde.','Der Dienst ist noch nicht verfügbar. Bitte aktualisieren Sie die Seite später manuell.','Сервис се још није вратио. Касније ручно освежите страницу.','서비스가 아직 복구되지 않았습니다. 나중에 페이지를 직접 새로고침하세요.'],
['重启失败：','Restart failed: ','Échec du redémarrage : ','Не удалось перезапустить: ','Error al reiniciar: ','再起動に失敗しました: ','Falha ao reiniciar: ','Neustart fehlgeschlagen: ','Поновно покретање није успело: ','다시 시작 실패: ']
]);})();
