(function(){'use strict';RFLang.register([
['检查更新','Check for updates','Rechercher des mises à jour','Проверить обновления','Buscar actualizaciones','更新を確認','Verificar atualizações','Nach Updates suchen','Провери ажурирања','업데이트 확인'],
['发现新版本','Update available','Mise à jour disponible','Доступно обновление','Actualización disponible','新しいバージョンがあります','Atualização disponível','Update verfügbar','Доступно је ажурирање','업데이트가 있습니다'],
['发现新版本 · {0}','Update available · {0}','Mise à jour disponible · {0}','Доступно обновление · {0}','Actualización disponible · {0}','新しいバージョン · {0}','Atualização disponível · {0}','Update verfügbar · {0}','Доступно ажурирање · {0}','업데이트 있음 · {0}'],
['当前已是最新版本','You’re using the latest version','Vous utilisez la dernière version','Установлена последняя версия','Tienes la versión más reciente','最新バージョンを使用しています','Você está usando a versão mais recente','Sie verwenden die neueste Version','Користите најновију верзију','최신 버전을 사용 중입니다'],
['暂时无法检查更新，请稍后重试。','Unable to check for updates right now. Please try again later.','Impossible de vérifier les mises à jour pour le moment. Réessayez plus tard.','Не удалось проверить обновления. Повторите попытку позже.','No se pueden buscar actualizaciones ahora. Inténtalo más tarde.','現在、更新を確認できません。後でもう一度お試しください。','Não foi possível verificar atualizações agora. Tente novamente mais tarde.','Updates können momentan nicht gesucht werden. Bitte später erneut versuchen.','Тренутно није могуће проверити ажурирања. Покушајте касније.','지금은 업데이트를 확인할 수 없습니다. 나중에 다시 시도하세요.'],
['更新检查','Update check','Vérification des mises à jour','Проверка обновлений','Comprobación de actualizaciones','アップデート確認','Verificação de atualização','Update-Prüfung','Провера ажурирања','업데이트 확인'],
['当前版本 {0} · 最新版本 {1}','Current version {0} · Latest version {1}','Version actuelle {0} · Dernière version {1}','Текущая версия {0} · Последняя версия {1}','Versión actual {0} · Última versión {1}','現在のバージョン {0} · 最新バージョン {1}','Versão atual {0} · Versão mais recente {1}','Aktuelle Version {0} · Neueste Version {1}','Тренутна верзија {0} · Најновија верзија {1}','현재 버전 {0} · 최신 버전 {1}'],
['更新说明','Release notes','Notes de version','Примечания к выпуску','Notas de la versión','リリースノート','Notas da versão','Versionshinweise','Белешке о издању','릴리스 노트'],
['取消','Cancel','Annuler','Отмена','Cancelar','キャンセル','Cancelar','Abbrechen','Откажи','취소'],
['下载更新包','Download update','Télécharger la mise à jour','Скачать обновление','Descargar actualización','更新をダウンロード','Baixar atualização','Update herunterladen','Преузми ажурирање','업데이트 다운로드'],
['此更新将从 GitHub 下载适用于本机系统的安装包。下载完成后，请退出 ReviewFlow 并运行安装包完成更新。','This downloads the installer for your system from GitHub. When the download finishes, quit ReviewFlow and run the installer to update.','Le programme d’installation pour votre système sera téléchargé depuis GitHub. Une fois le téléchargement terminé, quittez ReviewFlow et lancez-le pour effectuer la mise à jour.','Будет загружен установщик для вашей системы с GitHub. После загрузки закройте ReviewFlow и запустите установщик.','Se descargará desde GitHub el instalador para tu sistema. Al terminar, cierra ReviewFlow y ejecuta el instalador para actualizar.','お使いのシステム用インストーラーをGitHubからダウンロードします。完了したらReviewFlowを終了し、インストーラーを実行してください。','O instalador para seu sistema será baixado do GitHub. Quando terminar, feche o ReviewFlow e execute-o para atualizar.','Das Installationsprogramm für Ihr System wird von GitHub heruntergeladen. Beenden Sie nach dem Download ReviewFlow und starten Sie das Installationsprogramm.','Инсталатер за ваш систем биће преузет са GitHub-а. Када се преузимање заврши, затворите ReviewFlow и покрените инсталатер.','사용 중인 시스템용 설치 프로그램을 GitHub에서 다운로드합니다. 다운로드가 끝나면 ReviewFlow를 종료하고 설치 프로그램을 실행하세요.'],
['服务器部署不能从应用内更新，请联系管理员。','Server deployments cannot update from the app. Contact your administrator.','Les installations serveur ne peuvent pas être mises à jour depuis l’application. Contactez l’administrateur.','Серверную версию нельзя обновить из приложения. Обратитесь к администратору.','Las instalaciones de servidor no se pueden actualizar desde la aplicación. Contacta al administrador.','サーバー版はアプリから更新できません。管理者にお問い合わせください。','Instalações em servidor não podem ser atualizadas pelo app. Fale com o administrador.','Serverinstallationen können nicht über die App aktualisiert werden. Wenden Sie sich an die Administration.','Серверска инсталација се не може ажурирати из апликације. Обратите се администратору.','서버 배포는 앱에서 업데이트할 수 없습니다. 관리자에게 문의하세요.']
]);})();
